import type { ClientFull } from './types';

export const MOCK_CLIENTS: ClientFull[] = [
  {
    id: '1',
    nombre: 'Andrea Gómez',
    phone: '+54 9 11 4523-0987',
    address: 'Av. Rivadavia 4521, CABA',
    observations: 'Entra por la puerta lateral. Timbre nombre "Gómez". Llegar 5 min antes los lunes.',
    billing_cycle: 'monthly',
    billing_day: 30,
    billing_start_date: '2026-06-01',
    is_active: true,
    schedules: [
      { id: '1', day_of_week: 1, pickup_time: '07:30', return_time: '16:00', label: null, is_active: true },
      { id: '2', day_of_week: 2, pickup_time: '12:50', return_time: null, label: 'Escuela', is_active: true },
      { id: '3', day_of_week: 2, pickup_time: '14:05', return_time: null, label: 'Depto', is_active: true },
      { id: '4', day_of_week: 5, pickup_time: '08:15', return_time: '17:30', label: null, is_active: true },
    ],
    responsibles: [
      { id: '1', name: 'María Gómez', relationship: 'Familiar · mamá', status: 'linked' },
      { id: '2', name: 'Carlos Gómez', relationship: 'Familiar · papá', status: 'linked' },
      { id: '3', name: 'Laura Pérez', relationship: 'Cuidadora', status: 'pending' },
    ],
  },
  {
    id: '2',
    nombre: 'Bruno Ferreyra',
    phone: '+54 9 11 3821-4456',
    address: 'Corrientes 2340, CABA',
    observations: '',
    billing_cycle: 'biweekly',
    billing_day: null,
    billing_start_date: '2026-05-15',
    is_active: true,
    schedules: [
      { id: '5', day_of_week: 1, pickup_time: '08:00', return_time: '15:00', label: null, is_active: true },
      { id: '6', day_of_week: 3, pickup_time: '08:00', return_time: '15:00', label: null, is_active: true },
      { id: '7', day_of_week: 5, pickup_time: '08:00', return_time: '15:00', label: null, is_active: true },
    ],
    responsibles: [
      { id: '4', name: 'Ana Ferreyra', relationship: 'Familiar · mamá', status: 'linked' },
    ],
  },
  {
    id: '3',
    nombre: 'Camila Torres',
    phone: '+54 9 11 5678-1234',
    address: 'Palermo, Buenos Aires',
    observations: 'Llamar 10 minutos antes de llegar.',
    billing_cycle: 'weekly',
    billing_day: 5,
    billing_start_date: null,
    is_active: true,
    schedules: [
      { id: '8', day_of_week: 1, pickup_time: '07:00', return_time: '17:00', label: null, is_active: true },
      { id: '9', day_of_week: 2, pickup_time: '07:00', return_time: '17:00', label: null, is_active: true },
      { id: '10', day_of_week: 3, pickup_time: '07:00', return_time: '17:00', label: null, is_active: true },
      { id: '11', day_of_week: 4, pickup_time: '07:00', return_time: '17:00', label: null, is_active: true },
      { id: '12', day_of_week: 5, pickup_time: '07:00', return_time: '17:00', label: null, is_active: true },
    ],
    responsibles: [],
  },
  {
    id: '4',
    nombre: 'Diego Salinas',
    phone: '+54 9 11 2233-4455',
    address: 'Belgrano, Buenos Aires',
    observations: '',
    billing_cycle: 'monthly',
    billing_day: 1,
    billing_start_date: '2026-06-01',
    is_active: true,
    schedules: [
      { id: '13', day_of_week: 2, pickup_time: '09:00', return_time: null, label: null, is_active: true },
      { id: '14', day_of_week: 4, pickup_time: '09:00', return_time: null, label: null, is_active: true },
    ],
    responsibles: [
      { id: '5', name: 'Roberto Salinas', relationship: 'Familiar · papá', status: 'linked' },
    ],
  },
  {
    id: '5',
    nombre: 'Elena Ríos',
    phone: '+54 9 11 9988-7766',
    address: 'Villa Urquiza 1892',
    observations: 'Acceso por garage lateral.',
    billing_cycle: 'monthly',
    billing_day: 15,
    billing_start_date: '2026-06-01',
    is_active: true,
    schedules: [
      { id: '15', day_of_week: 1, pickup_time: '08:30', return_time: '16:30', label: null, is_active: true },
      { id: '16', day_of_week: 5, pickup_time: '08:30', return_time: '16:30', label: null, is_active: true },
    ],
    responsibles: [],
  },
  {
    id: '6',
    nombre: 'Facundo Méndez',
    phone: '+54 9 11 1122-3344',
    address: 'Caballito, Buenos Aires',
    observations: '',
    billing_cycle: 'monthly',
    billing_day: 1,
    billing_start_date: '2026-01-01',
    is_active: false,
    schedules: [],
    responsibles: [],
  },
];
